### ISSUE TITLE
Ver 2.9.0 Shipping Package Build Failed

### ISSUE THREAD

**Issue by rollaroll** [heroiclabs/nakama-unreal#105]
**When I use shipping mode to package the project, the build phase failed, and part of the error log is:**
```
Compile module: MessageLog
Missing precompiled manifest for 'MessageLog', 'C:\Program Files\EpicGames\UE 5.1\Engine\Intermediate\Build\Win644\UnrealGame\Shipping\MessageLog\MessageLog.precompiled'. This module was most likely noot
flagged for being included in a precompiled build - set 'PrecompileForTargets = PreecompileTargetsType.Any;' in MessageLog.bild.cs to
override. If part of a plugin, also chleck if its 'Type' is correct.
```
**After deleting "NakamaTests" in the "Modules" section of the Nakama.uplugin file, the packaged build can pass normally.**

**Comment by lugehorsam** [comment]
Thanks @rollaroll we'll take a look and let you know in a few days.

**Comment by lugehorsam** [comment]
Hey @rollaroll we have identified a potential fix but are having trouble reproducing the issue.

Could you share your UE version and host + target platform when making the build?
