### ISSUE TITLE
Tried to make Android package and got link error

### ISSUE THREAD

**Issue by Chr1sL1** [heroiclabs/nakama-unreal#116]
![image](https://github.com/heroiclabs/nakama-unreal/assets/1808616/3c6ba0f9-5c1a-4ed6-85ab-980b4638b20a)

**Comment by lugehorsam** [comment]
Hey @Chr1sL1 can you share which version of nakama-unreal you are on? We also recommend migrating to our `NakamaUnreal` module.

**Comment by Chr1sL1** [comment]
It's Version 2.9.1

**Comment by lugehorsam** [comment]
@Chr1sL1 are you using our native Unreal types? 

Could you remove your dependency on `NakamaCore` in your Unreal Module file? It is no longer needed in order to use the `NakamaUnreal` module.

**Comment by Chr1sL1** [comment]
> @Chr1sL1 are you using our native Unreal types?
> 
> Could you remove your dependency on `NakamaCore` in your game's Unreal module file? It is no longer needed in order to use the `NakamaUnreal` module.

I just tried to remove NakamaCore with the project regenerated and rebuilt, sadly it doesn't work. Still showed the same error.

**Comment by lugehorsam** [comment]
@Chr1sL1 the issue originates from Nakama Core so somehow it's still making its way into your project.

Could you share your module file?

**Comment by Chr1sL1** [comment]
Here is the .uplugin file:
![image](https://github.com/heroiclabs/nakama-unreal/assets/1808616/5bb5a127-2a6b-432a-977f-e295e975ce5d)

and here is my build.cs file:
![image](https://github.com/heroiclabs/nakama-unreal/assets/1808616/6c1a7100-68f4-4f2a-84f4-44a70974598b)

**Comment by lugehorsam** [comment]
Thanks. One more question for you @Chr1sL1 -- if you remove the `NakamaCore` folder and the `NakamaCore` reference in the `.uplugin` file, does that resolve your issue?

**Comment by Chr1sL1** [comment]
Sorry for the late replay but I tried to remove NakamaCore, finally it worked! thank you for your help!
