### ISSUE TITLE
Unrecognized type 'TObjectPtr' - type must be a UCLASS, USTRUCT or UENUM when trying to build project

### ISSUE THREAD

**Issue by jonathanatn** [heroiclabs/nakama-unreal#118]
I'm getting an error when trying to build the project after adding the Nakama plugin to Unreal 4.27.2:

> Error Unrecognized type 'TObjectPtr' - type must be a UCLASS, USTRUCT or UENUM	\Plugins\Nakama\Source\NakamaUnreal\Public\NakamaRealtimeClient.h	1369

**Comment by lugehorsam** [comment]
Hey @jonathanatn this should now be fixed in the latest release (v2.9.5), thanks.
