### ISSUE TITLE
UNakamaClient HTTP request memory leak?

### ISSUE THREAD

**Issue by mstile1** [heroiclabs/nakama-unreal#124]
It appears that all http requests 'leak'? by capturing itself in the `OnProcessRequestComplete `delegate. The shared ptr is stored inside a delegate that it owns and the request will never die.

Capturing the `HttpRequest `should be redundant as it's passed in as the first param?

`HttpRequest->OnProcessRequestComplete().BindLambda([SuccessCallback, ErrorCallback, this, HttpRequest](FHttpRequestPtr Request, FHttpResponsePtr Response, bool bSuccess) {`

**Comment by mstile1** [comment]
This manifested as an issue for me as I was capturing a shared ptr in the success and error callbacks that was never getting destroyed.

**Comment by lugehorsam** [comment]
Thanks @mstile1 we've added a fix to our upcoming release: https://github.com/heroiclabs/nakama-unreal/pull/123

If you try out that release, do you still see your shared ptr not getting destroyed?

**Comment by mstile1** [comment]
Thanks for the quick response! I will grab that release when I can, but it looks reasonable as I had already made the same changes locally to test my issue was resolved.

**Comment by mstile1** [comment]
I can confirm with release #123, the TSharedRef<> I'm capturing in my success and error callbacks is getting destroyed.

**Comment by lugehorsam** [comment]
Thanks @mstile1 v2.9.7 has been released now.
