### ISSUE TITLE
Add client guide.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-unreal#13]
This work needs to be submitted against the [nakama-docs](https://github.com/heroiclabs/nakama-docs) repository so we can publish it directly on the website.

Follow this guide format: https://github.com/heroiclabs/nakama-docs/blob/master/docs/android-java-client-guide.md

**Comment by mofirouz** [comment]
This should also include whatever necessary to guide developers to integrate Unreal client in their project, and optionally use Blueprints if they need.

**Comment by Dimon4eg** [comment]
Done
