### ISSUE TITLE
Upgrade to Nakama 2.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-unreal#14]
Currently the client is compatible with Nakama 1.4.x. We should update the client to use Nakama 2 and use [Nakama C++ Client](https://github.com/heroiclabs/nakama-cpp) as much as possible to minimise code duplication.

The client should work on Desktop, iOS, Android and as many other target outputs as possible.

**Comment by mofirouz** [comment]
We should target at least Unreal v4.21 - as that's what most people told us they use.

**Comment by mofirouz** [comment]
Also make sure that SSL is fully supported.

**Comment by Superxwolf** [comment]
Is there any release window for this? Also wondering for Android as Unreal 4.21 uses Android NDK r14b and the current Nakama C++ Client does not support it.

**Comment by Dimon4eg** [comment]
Released 2.0.3 with support server 2.x, SSL and Unreal 4.21 for Mac, iOS and Windows. 
Android is not supported yet because Unreal uses gnustl which we don't support because grpc does not support it. Also gnustl was removed from NDK 18.
So Unreal should support at least NDK 18

**Comment by novabyte** [comment]
Thanks @Dimon4eg I'll close this issue and a new one can be opened whenever a request comes in to track specific requests on the 2.0 client.

**Comment by Dimon4eg** [comment]
Android support has been added in [2.1.0](https://github.com/heroiclabs/nakama-unreal/releases/tag/v2.1.0) but better to use latest [release](https://github.com/heroiclabs/nakama-unreal/releases/latest)
