### ISSUE TITLE
Unable to import class c ++ plugin ue4 into a new project.

### ISSUE THREAD

**Issue by julienBouysset** [heroiclabs/nakama-unreal#2]
Unable to import class c ++ plugin ue4 into a new project.

**Comment by mofirouz** [comment]
Hey @julienBouysset Can you paste in the errors that you get, along with all the environment information and version of your OS and Unreal please?

I'll have a look at this in the next few days.

**Comment by julienBouysset** [comment]
error is : "MyClass.h" not find,

**Comment by julienBouysset** [comment]
I managed to find the plugin (I installed the plugin in the game engine) but I have this error 

Error LNK1181 unable to open file 'E: \ Software \ Epic Games \ UE_4.16 \ Engine \ Plugins \ Nakama \ nakama \ Intermediate \ Build \ Win64 \ UE4Editor \ Development \ UE4Editor-Nakama.lib' WorldOfBattle D: \ Unreal Engine Project \ WorldOfBattle \ Intermediate \ ProjectFiles \ LINK 1

**Comment by julienBouysset** [comment]
I found the solution you have to copy the code in the plugins of the project before the comilation in C ++ if not VS can not see the file and will therefore generate an error.
