### ISSUE TITLE
CopyToBinaries is consistently problematic

### ISSUE THREAD

**Issue by crowder** [heroiclabs/nakama-unreal#21]
When building or generating a VS project with the Unreal editor open, I am frequently encountering an exception along the lines of:

`WARNING: Exception while generating include data for nakama_testEditor: Unable to instantiate module 'Nakama': System.Exception: Failed to copy file: The process cannot access the file 'C:\Users\crowd\Documents\Unreal Projects\NakamaUnrealProto\Plugins\Nakama\Source\Nakama\..\..\..\..\Binaries\Win64\nakama-cpp.dll' because it is being used by another process`

I am left wondering what the purpose is of this `CopyToBinaries` step in the build?

**Comment by Dimon4eg** [comment]
Cannot reproduce.
What nakama-unreal version do you use?

Purpose of `CopyToBinaries` is to copy `nakama-cpp.dll` to binaries folder of your project.
