### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by friuns2** [heroiclabs/nakama-unreal#25]
Hello is there example project? 

if i have my project made with standart unreal networking, and i connect this plugin will it work out of the box?

**Comment by Dimon4eg** [comment]
We are going to create simple example.

About standard unreal networking, it’s separate feature of the engine. You usually choose between one or the other based on your multiplayer requirements and game design. If you’re working on a 3D physics shooter then headless Unreal instances is the best fit unless you want to replicate large portions of the engine in Go (or C) to use with Nakama. For most other game types like MOBA, Turn-based, etc, etc it really depends on your game design but Nakama will fit well.

**Comment by lugehorsam** [comment]
Hey @friuns2 we now include a sample project in this repository.
