### ISSUE TITLE
Can't call RPCs: cannot unmarshal object into Go value of type string

### ISSUE THREAD

**Issue by DeoVolenteGames** [heroiclabs/nakama-unreal#26]
I'm trying to write an extension plugin to use Nakama C++ from Blueprints. I have authentication working, and I have set it up so I call functions like `getAccount()` or `listStorageObjects()`, but I can't get it to call RPCs. When I try I get the error `json: cannot unmarshal object into Go value of type string`. I've tried sending with the minimum amount of arguments (only session and RPC ID) and it still errors in the same way. Do you know why I'm having trouble? My code looks something like:

```cpp
auto Success = [this](const NRpc& RPC) { BroadcastSuccess(OnSuccess, FNakamaRPCResponse(RPC)); };
auto Error = [this](const NError& Error) { BroadcastError(OnError, Error); };

NakamaBP::Client->rpc(
	NakamaBP::Session,
	std::string(TCHAR_TO_UTF8(*RpcID)),
	std::string(TCHAR_TO_UTF8(*Payload)),
	Success,
	Error);
```

**Comment by Dimon4eg** [comment]
This issue has been fixed and new release is coming soon.
Currently you can call rpc by socket, it will work.

**Comment by mofirouz** [comment]
@DeoVolenteGames it would be amazing if you could open-source and contribute back your Blueprint plugin. Let me know if you’d like to contribute and/or directly integrate that into the Nakama Unreal client library 🙏

**Comment by DeoVolenteGames** [comment]
@Dimon4eg Thanks for the quick fix! I should be able to make do for now. I'm just glad to know that I wasn't doing anything silly.

@mofirouz I'd love to do that, but I have a couple of reservations. The biggest is that I'd have to check with my employer to see if my contract will allow me to do that. I'm also not super skilled with C++ so I'm not sure about the quality of my work, but I suppose open-sourcing it would be a great way to improve it. And finally, the project might change a lot as I want to try generating parts of it so I don't have to write so much boilerplate by hand like I'm doing right now. 

If I do get the opportunity to release it open-source what's the best way to let you know? I'd like to keep you in the loop with my progress if it's something that you're interested in. Should I just post in issue #15?

**Comment by Dimon4eg** [comment]
I suggest to move Blueprint discussion to that issue.

**Comment by Dimon4eg** [comment]
Fixed in https://github.com/heroiclabs/nakama-unreal/releases/tag/v2.2.4
