### ISSUE TITLE
UE 4.24 Build error

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama-unreal#27]
UnrealBuildTool : error : Unable to instantiate module 'Nakama': System.Exception: Failed to copy file: Could not find a part of the path 'F:\UnrealProjects\TheLastPiece\Plugins\Nakama\Source\Nakama\Private\shared-libs\win64\v142\Release\nakama-cpp.dll'.
1>                           at Nakama.CopyFile(String source, String dest) in f:\UnrealProjects\TheLastPiece\Plugins\Nakama\Source\Nakama\Nakama.Build.cs:line 213
1>                           at Nakama.CopyTo(String Filepath, String toPath) in f:\UnrealProjects\TheLastPiece\Plugins\Nakama\Source\Nakama\Nakama.Build.cs:line 176
1>                           at Nakama.HandleWindows(ReadOnlyTargetRules Target) in f:\UnrealProjects\TheLastPiece\Plugins\Nakama\Source\Nakama\Nakama.Build.cs:line 110
1>                           at Nakama..ctor(ReadOnlyTargetRules Target) in f:\UnrealProjects\TheLastPiece\Plugins\Nakama\Source\Nakama\Nakama.Build.cs:line 42
1>                        (referenced via default plugins -> Nakama.uplugin)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "C:\UnrealEngine\UnrealEngine\Engine\Build\BatchFiles\Build.bat -Target="TheLastPieceEditor Win64 Development -Project=\"F:\UnrealProjects\TheLastPiece\TheLastPiece.uproject\"" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "TheLastPiece.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

**Comment by ANURAGX** [comment]
Shit, now after removing the plugin my project is not compiling.
Is this plugin corrupts other project, if so rename it to nakama-corrupter.

**Comment by mofirouz** [comment]
Nakama-Unreal is used by many developers in the world without any issues. In addition, your comment is not helpful nor an acceptable way of expressing your problems. I've deleted it for now, please come back with more information so we can help you pinpoint the issue.

**Comment by Dimon4eg** [comment]
@ANURAGX what Nakama plugin version do you use?
2.2.4 works for me with UE 4.23 and 4.24

**Comment by ANURAGX** [comment]
UE 4.24
Master branch

**Comment by Dimon4eg** [comment]
Don't use from just from github, it does not contain binary files.
Download release from here https://github.com/heroiclabs/nakama-unreal/releases/latest

**Comment by ANURAGX** [comment]
Ok Got it. Thanks
