### ISSUE TITLE
XBox/Platstation or Nintendo Switch Support.

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama-unreal#28]
As I can can see in plugin the whitelisted platforms are Windows, Android, iOS, Linux and MAC.
Is there a plan for console platforms ?
Is there any work around to them work on consoles.

**Comment by mofirouz** [comment]
We work with game studios directly to enable console support. Please email us directly from your studio and we can coordinate integration Nakama with the required consoles.
