### ISSUE TITLE
new function health-check

### ISSUE THREAD

**Issue by julienBouysset** [heroiclabs/nakama-unreal#33]
Function to use as a healthcheck for reaching the server with the correct connection credentials.

**Comment by mofirouz** [comment]
Can you elaborate what you mean by this? Would a simple custom RPC function work in here? Or connecting via a socket to the server?

**Comment by novabyte** [comment]
@julienBouysset I recommended we have a discussion about this feature. It's a nice way for the game client to check that the credentials set in code are correct. Probably most useful where you might switch the values often between development and production settings.

**Comment by Dimon4eg** [comment]
@novabyte how do you propose to check connection credentials?

**Comment by julienBouysset** [comment]
currently I forgot to launch the nakama server, it will be the same result on a game in production for an update of the server for example. So for this case the connection to the server 'createDefaultClient' does not return an error, so it would be interesting to create or be a function to verify that the server and joiniable be returns an injoinable error server.

**Comment by Dimon4eg** [comment]
After creating client you should perform authentication and it will fail with `ConnectionError` if connection credentials are wrong or server is down

**Comment by novabyte** [comment]
I think the decision is whether to leave the check for reachability for the first HTTP request (usually an authentication request) or to provide a function that can be specifically used to check the credentials are good (and therefore the server is reachable).

After this discussion my thought is that there's just not enough gained by a separate function to do a reachability check on the server connection credentials which couldn't be done with an authentication request which would likely happen next anyway in most game logic.
