### ISSUE TITLE
Failed to compile in Unreal 4.23.1

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama-unreal#37]
I'm trying to add Nakama-Unreal to an empty unreal project but I get the following error at compile (Project startup):
`Failed to copy file: Could not find a part of the path 'C:\Users\Superxwolf\Documents\Unreal Projects\NakamaWrapperProject\Plugins\Nakama\Source\Nakama\Private\shared-libs\win64\v141\Release\nakama-cpp.dll'.`
Also `LogInit: Warning: Incompatible or missing module: Nakama` a bit before,.

For Unreal 4.23.1

**Comment by Dimon4eg** [comment]
Did you download the latest release https://github.com/heroiclabs/nakama-unreal/releases/tag/v2.3.0 ?

**Comment by Superxwolf** [comment]
That was the issue, I downloaded the master branch rather than from the release page, thanks!

**Comment by novabyte** [comment]
@Dimon4eg Do you think we should do a new release to make sure this is permanently solved?

**Comment by Superxwolf** [comment]
What caught me off was Step 4 of Getting Started that just says `nakama-unreal`, I thought it just meant the repo, I didn't realize the link is to Release.

**Comment by Dimon4eg** [comment]
No new release needed. Issue not with release.
