### ISSUE TITLE
Error compiling unreal project with nakama-unreal

### ISSUE THREAD

**Issue by G0nzzzz** [heroiclabs/nakama-unreal#4]
Hi. My name is Ehm, I'm part of a research group on digital game based learning at Fraunhofer. Currently I'm evaluating Multiplayer-frameworks for our game projects (UE4 based). 

I set up a server on a linux system and a new UE project (version 4.15.3) following the guide given in README.MD. When I tried to compile the project in VS2015, I get some errors:

'Messages while compiling \Unreal Projects\NakamaTest\Intermediate\Build\BuildRules\NakamaTestModuleRules.dll:

Nakama.Build.cs(9,49): error CS1729: 'UnrealBuildTool.ModuleRules' enthält keinen Konstruktor, der 1-Argumente akzeptiert.'
\Nakama.Build.cs(28,9): error CS1502: Die beste Übereinstimmung für die überladene 'UnrealBuildTool.ModuleRules.AddEngineThirdPartyPrivateStaticDependencies(UnrealBuildTool.TargetInfo, params string[])'-Methode hat einige ungültige Argumente.

Nakama.Build.cs(28,54): error CS1503: Argument '1': Konvertierung von 'UnrealBuildTool.ReadOnlyTargetRules' in 'UnrealBuildTool.TargetInfo' nicht möglich.

Nakama.Build.cs(38,24): error CS1061: 'UnrealBuildTool.ReadOnlyTargetRules' enthält keine Definition für 'Platform', und es konnte keine Erweiterungsmethode 'Platform' gefunden werden, die ein erstes Argument vom Typ 'UnrealBuildTool.ReadOnlyTargetRules' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).

And a couple more related lines. Any idea what went wrong here?

**Comment by novabyte** [comment]
@G0nzzzz Thanks for the issue report. With the 1.0 release of the server launched in the first week of August we're in the middle of various client sprints. We've just added an official Java client, and have Swift, and JavaScript clients in development.

Now that the server protocol is backwards compatible we'll also update the Unreal client. I think right now the client is compatible with the 0.13.1 release of Nakama server.

**Comment by Renanse** [comment]
I believe the issue you have pasted above is caused by a change in the API in Unreal 4.16 (our current requirement.)  We do not currently attempt to be backwards compatible across API breaking changes that Epic does, but perhaps when Nakama-Unreal 1.0 is released we can go back and add support for older versions of Unreal.

Also, it is worth noting that we only officially support windows 64 at this time.  Even with the correct version of Unreal, you would run into missing Linux binaries for protobuf 3.1.0 (though you could always generate those and contribute them back. :) )

**Comment by paultech** [comment]
Nakama.Build.cs 
line 9 should look like:
	public Nakama(ReadOnlyTargetRules Target) : base(Target)
line 60:
    private bool LoadProtobufLib(ReadOnlyTargetRules Target)

Should work fine after that

**Comment by Renanse** [comment]
@paultech Not sure if you had changes to point out?  Those 2 lines already match what is currently in master (since May 30.)

**Comment by G0nzzzz** [comment]
@Renanse Thanks, I can confirm that it works with 4.16.3 (not with 4.17.0 though)

**Comment by paultech** [comment]
@Renanse You are correct, during upgrade to 4.17 I applied that patch universally to all build.cs files and mistakenly believed Nakama was included.

@G0nzzzz This is working on 4.17 for me on Win64 & Linux64
