### ISSUE TITLE
Incorrect build for iOS

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama-unreal#40]
Hello,

We were testing builds today, and we managed to make an iOS build, however upon launching it it crashes with the following error:

`Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/libnakama-cpp.dylib' not found for '/private/var/containers/Bundle/Application/EC19A581-3AAF-4685-BBD0-0D641373A09B/Riddlr.app/Riddlr', tried but didn't find: '/private/var/containers/Bundle/Application/EC19A581-3AAF-4685-BBD0-0D641373A09B/Riddlr.app/Frameworks/libnakama-cpp.dylib' '@rpath/libnakama-cpp.dylib' '/usr/local/lib/libnakama-cpp.dylib' '/usr/lib/libnakama-cpp.dylib'`

We made sure to download the iOS version and have libnakama-cpp.dylib in the specified iOS directory. We were able to build succesfully for Mac and Android, only iOS is giving us this issue.

EDIT: We are using Unreal 4.24

**Comment by Yanovskiy** [comment]
@Superxwolf Have you solved this problem?

**Comment by Superxwolf** [comment]
No. We talked with the Nakama team around when the issue was opened but not much progress was made with them. We gave up on Nakama Unreal for iOS since we never found a fix for it.

**Comment by lugehorsam** [comment]
Hey @Superxwolf and @Yanovskiy we've done a new iOS release for Unreal.
