### ISSUE TITLE
Handle UTF-8 characters beyond the ASCII range off the socket

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama-unreal#41]
An issue reported by @LinXunxi on Nakama server indicates that UTF-8 is not decoded correctly off the socket:

https://github.com/heroiclabs/nakama/issues/478

The example is with Chinese characters but it's probable that anything beyond the ASCII range is not decoded correctly.

**Comment by Dimon4eg** [comment]
The sdk supports UTF-8.
Closing as the issue is resolved by user.
