### ISSUE TITLE
2.5.0 removed android and ios support?

### ISSUE THREAD

**Issue by SnappierSoap318** [heroiclabs/nakama-unreal#49]
When trying to package project with the latest plugin version, build fails, showing this error 
![image](https://user-images.githubusercontent.com/42905211/135231897-62909afa-0489-493a-8b87-46ab85a9c899.png)

Packaging with 2.4.0 fixes this issue, but we are unable to use the new real-time party feature.

**Comment by Albertcleetus** [comment]
Yeah. Same issue happen here. may be nakama dev team fix this soon.
In older version build completes perfect.

**Comment by lugehorsam** [comment]
@SnappierSoap318 and @Albertcleetus we've done a new release that should resolve this issue.
