### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by gustavotero7** [heroiclabs/nakama-unreal#5]
Hi, The doc links aren't working, where I can find documentation about the Nakama Unreal client?

**Comment by novabyte** [comment]
@gustavotero7 We recently overhauled our developer docs with our 1.0 server release. We'd planned to rewrite all documentation but ran out of time. We've got our JavaScript client almost complete and have documentation work for it and the Unreal client in the works. 

In the meantime the code is the main reference on the API. The Unity client uses a similar API pattern as the Unreal code so it should help with the structure of the code.

**Comment by gustavotero7** [comment]
Yes, I already integrated it, thanks :)
