### ISSUE TITLE
ld.lld: error: unable to find library -lnakama-cpp

### ISSUE THREAD

**Issue by brendenfrank** [heroiclabs/nakama-unreal#50]
When compiling to linux, we get the following error:
ld.lld: error: unable to find library -lnakama-cpp

**Comment by hux** [comment]
You need to make sure the libnakama-cpp.so is included in your project folder:

My_Project/Plugins/Nakama/Source/Nakama/Private/shared-libs/linux/x64/libnakama-cpp.so

Since originally we were building on Windows, we had that missing dependency there
