### ISSUE TITLE
Cannot use PartyMatch as the type runtime.MatchType

### ISSUE THREAD

**Issue by rpvela** [heroiclabs/nakama-unreal#51]
In function createPartyMatch

https://github.com/heroiclabs/nakama-unreal/blob/master/online_party_system/party.go#L53

```log
Cannot use '&amp;PartyMatch{config: config,}' (type *PartyMatch) 
as the type runtime.MatchType does not implement 'runtime.Match' 
as some methods are missing:MatchSignal(ctx context.Context, 
logger Logger, db *sql.DB, nk NakamaModule, 
dispatcher MatchDispatcher, tick int64, state interface{}, data string) (interface{}, string)
```

**Comment by mofirouz** [comment]
Hi @rpvela; This isn't a code issue relevant to the Unreal SDK. Please post questions on the forum: https://forum.heroiclabs.com

In the interest of closing this issue with an answer;

- `MatchSignal` was added in a more recent version of Nakama, you'll need to follow this documentation to add the respective function reference in: https://heroiclabs.com/docs/nakama/concepts/server-authoritative-multiplayer/#match-handler-api_1

- In recent versions of Nakama, we've added first-class support for Parties: https://heroiclabs.com/docs/nakama/concepts/parties/
