### ISSUE TITLE
iOS runtime issue

### ISSUE THREAD

**Issue by brian-asyncedge** [heroiclabs/nakama-unreal#54]
There has not been a ios build of nakama-cpp since 2.4.0 and nakama-unreal removed the library in v2.5.0.

When I try to use the 2.4.0 ios dylib I can compile the iOS version but the runtime crashes failing to load the library. 

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/libnakama-cpp.dylib
Referenced from: /private/var/containers/Bundle/Application/9C43C5E8-CF5D-4D66-9603-B9F25D741FF2/ServiceProtoClient.app/ServiceProtoClient
Reason: tried: '/private/var/containers/Bundle/Application/9C43C5E8-CF5D-4D66-9603-B9F25D741FF2/ServiceProtoClient.app/Frameworks/libnakama-cpp.dylib' (no such file), '/private/var/containers/Bundle/Application/9C43C5E8-CF5D-4D66-9603-B9F25D741FF2/ServiceProtoClient.app/Frameworks/libnakama-cpp.dylib' (no such file), '/usr/local/lib/libnakama-cpp.dylib' (no such file), '/usr/lib/libnakama-cpp.dylib' (no such file)
(terminated at launch; ignore backtrace)

What is the status of iOS support with nakama-unreal?

**Comment by mofirouz** [comment]
At the moment, we cannot support iOS builds due to dependency constraints. 

Whilst I cannot provide a timeline for a fix, this is something we are actively working on. If you are interested in alpha builds, when available, please email me directly (mo@heroiclabs). Thanks!

**Comment by brian-asyncedge** [comment]
Thanks for the update!

**Comment by lugehorsam** [comment]
Hey @brian-asyncedge we've released a new iOS build for Unreal.
