### ISSUE TITLE
UE5 version

### ISSUE THREAD

**Issue by LittleOldXander** [heroiclabs/nakama-unreal#55]
Is there a tutorial to compile it for UE5 (sorry not very familiar with UE5). Seems that UE5 expects me to compile it manually ?
Sorry if it's a stupid question.

**Comment by lugehorsam** [comment]
@LittleOldXander we don't have a UE5 tutorial at the moment. What happens if you use a prebuilt library instead? Could you share why you think it expects you to compile the library from source?

**Comment by LittleOldXander** [comment]
Hey, well it said it needed to recompile from source.
![image](https://user-images.githubusercontent.com/48095760/166414876-e2feceb9-94be-47b6-9400-746c126280c2.png)
![image](https://user-images.githubusercontent.com/48095760/166414924-fe54d207-9b7d-4ff2-ad3e-64452f951faa.png)

Dunno if it meant the project in vs or the plugin only, When i try to rebuild the project in VS it throws these errors :
![image](https://user-images.githubusercontent.com/48095760/166415053-39a942d3-9119-468a-83f8-17f6f1712a3a.png)

Please note that before following the steps in the readme the project rebuilding works just fine. I can solve the Win32 error by simply removing the references to it from the code (as i dont necessarily need Win32) but the other issues i dont know how to solve.

**Comment by lugehorsam** [comment]
Hey @LittleOldXander we did a new release and this issue should now be resolved.
