### ISSUE TITLE
Where do we being ?

### ISSUE THREAD

**Issue by syedalamabbas** [heroiclabs/nakama-unreal#6]
Hello nakama community !
              I am trying to use nakama server with unreal engine. I downloaded the plugin from https://github.com/heroiclabs/nakama-unreal. I checked in my test c++ project that the plugin is activated.
I have installed nakama server on VMware ubuntu.
I can view the  Cockroach Dashboard at 
VM_ip-address:8080/   
and 
nakama server dashboard at 
VM_ip-address:7351/   

However, the documentation for using this in an unreal project is not clear.
One of my questions is where do I add this code:

```
#include "NClient.h"
NClient client = NClient::Default("defaultkey");
```

I mean where do I begin? 
I tried different classes in unreal engine framework - the most common are Actor class objects, by creating a dummy but I get an undefined compile error.  I also tried derived UGameInstance class. 
I feel there is something missing from the settings of the nakama-unreal.

**Comment by luochuanyuewu** [comment]
You can create an actor component subclass as a start point. Override begin play event to init your nakama client.

**Comment by syedalamabbas** [comment]
I think the there is a better way than directly working with NClient at an actor level, but it is not properly documented, see my next issue on this repository where I show how to use it. But there are some problems.

**Comment by mofirouz** [comment]
I'm closing this as this is currently being tracked on #13 .
