### ISSUE TITLE
About iOS Support

### ISSUE THREAD

**Issue by GameInstitute** [heroiclabs/nakama-unreal#69]
First of all, all code are based on my Android support PR, #71 

1. Create a folder in `libnakama/ios-arm64`, named it `nakama-sdk.emeddedframework`.
2. Move `nakama-sdk.framework` in `nakama-sdk.emeddedframework`.
3. Copy `Headers` folder to `libnakama/ios-arm64`, for include in plugin.
4. Zipped `nakama-sdk.emeddedframework` to `nakama-sdk.emeddedframework`.
5. Modify NakamaCore.build.cs:
```cpp
else if (Target.Platform == UnrealTargetPlatform.IOS)
{
        var frameworkDir = Path.Combine(ModuleDirectory, "libnakama", "ios-arm64");
	var frameworkZip = Path.Combine(frameworkDir,"nakama-sdk.emeddedframework.zip");
	PublicAdditionalFrameworks.Add(new Framework("nakama-sdk",frameworkZip,"",true));
		   
        PublicIncludePaths.Add(Path.Combine(frameworkDir, "Headers"));
}
```
The hierarchy of nakama-sdk.emeddedframework.zip was:
```
nakama-sdk.emeddedframework.zip
---nakama-sdk.emeddedframework
------nakama-sdk.framework
---------Headers
---------Info.plist
---------nakama-sdk
```
The same way couldn't used for Mac OS, I would work on it if I had enough time .

**Comment by lugehorsam** [comment]
Thanks @GameInstitute I see you add this to https://github.com/heroiclabs/nakama-unreal/pull/68

**Comment by GameInstitute** [comment]
Of course. I submitted it.
