### ISSUE TITLE
Update to latest server version

### ISSUE THREAD

**Issue by opcon** [heroiclabs/nakama-unreal#8]
Are there any plans to update this c++ client to the latest Nakama server (version 1.3.0)?

**Comment by novabyte** [comment]
@opcon Yes absolutely. The protocol changes are very minor. I'll discuss it and we'll add it to a sprint plan.

**Comment by luochuanyuewu** [comment]
@novabyte  How about updating to nakama 1.4 version?

**Comment by janimm** [comment]
Is nakama-unreal up to date with current server?

We are having issues parsing the replys from server, for example NSession.cpp:84 if (d.HasMember("handle")). It seems like server reply for login is "han", not "handle".

**Comment by novabyte** [comment]
@janimm Sorry. Things slipped behind schedule because of the Christmas break. We have plans to update the Unreal client for small changes added in 1.4.0 release of the server. Would also be happy to receive a pull request if you have time.

**Comment by janimm** [comment]
@novabyte Thanks! While you are at it, it would be great if you can update some basic types, like uint8 to uint8_t.

We are building a custom solution based on nakama-unreal and those changes are required to cross-compile.

**Comment by janimm** [comment]
Any ETA for updating this to match latest server?

**Comment by mofirouz** [comment]
As @novabyte mentioned we have plans but none that are in action at the moment. It would be great if you could provide some community love and open a couple of PRs for this project :)

**Comment by janimm** [comment]
I have tried to share all my experiences about using this lib with custom c++ solutions. But I'm unable to fix the server version mismatch for you.

Take action, please. I understood that changes between current server and Unreal lib are minor. I can try to help you with generic c++ implementation as soon as we are able to ship our product.

**Comment by Renanse** [comment]
I have updated master to target Nakama server version 1.4.0 as well as added a fix for the session parsing issue mentioned above.

**Comment by mofirouz** [comment]
@Renanse You are a star sir - thank you :)
