### ISSUE TITLE
How about the support on android ? Thank you

### ISSUE THREAD

**Issue by KMUS1997** [heroiclabs/nakama-unreal#82]
I can not add "Android" to the white list  ,and can not packaging a well app to work now?

**Comment by lugehorsam** [comment]
Hey @KMUS1997 you can integrate the package off of master for Android support until we put together our next release.

**Comment by KMUS1997** [comment]
hello, when can we get a  android  sdk. I can not keep myself on using it

**Comment by lugehorsam** [comment]
We've made a new release with Android support: https://github.com/heroiclabs/nakama-unreal/releases/tag/v2.7.0

**Comment by KMUS1997** [comment]
@lugehorsam Thank you 。so powerful ,thank your effort
