### ISSUE TITLE
UNakamaRealtimeClient::PartyDataReceived delegate doesn't work

### ISSUE THREAD

**Issue by GregoryBolshakov** [heroiclabs/nakama-unreal#87]
If I add some function to the PartyDataReceived delegate, it is never called. 

I do it in this way:
```
FOnReceivedPartyData ReceivedPartyDataDelegate;
ReceivedPartyDataDelegate.AddDynamic(this, &UNakamaManager::OnPartyDataReceived);

NakamaRealtimeClient->PartyDataReceived = ReceivedPartyDataDelegate;
NakamaRealtimeClient->SetListenerPartyDataCallback();
```

Then I call NakamaRealtimeClient->SendPartyData() with a valid party id. NakamaRealtimeClient is set up and authorized properly, but `OnPartyDataReceived` isn't called

**Comment by lugehorsam** [comment]
Hey @GregoryBolshakov is the client doing the listening for the party data the same client that's sending out the data?

**Comment by GregoryBolshakov** [comment]
@lugehorsam Yes, the same

**Comment by lugehorsam** [comment]
@GregoryBolshakov okay -- that's the issue here. A user cannot send party data to themself.
