### ISSUE TITLE
Cursor in BluePrint Node ”ListNotifications“ not work

### ISSUE THREAD

**Issue by rollaroll** [heroiclabs/nakama-unreal#88]
No matter what value is set for the Cursor，returned  NotificationsList is always start from begin

**Comment by rollaroll** [comment]
Cursor In BluePrint Node ”GetFriends“ doesn't work either, When pass the previous returned cursor to it, Get Log:
LogTemp: Error: [Nakama::RestClient::reqError] NError: InvalidArgument
message: Cursor is invalid.

**Comment by rollaroll** [comment]
> Hey @rollaroll is this still an issue for you in the latest release?

After testing, this issue has been fixed in version 2.9.0. 
But I found a new issue in 2.9.0, please see my new commit in issues.

**Comment by lugehorsam** [comment]
Thanks @rollaroll we'll close this out and address the other one.
