### ISSUE TITLE
Call unknown function createDefaultClient

### ISSUE THREAD

**Issue by on7line** [heroiclabs/nakama-unreal#91]
I can compile the BP and debug game,but when it is saved and reopen project,the error is "Call unknown function createDefaultClient"

UE5.1  C++ ThirdPersionProject 

Thanks!

![image](https://user-images.githubusercontent.com/9068655/233834540-411e2270-c9bb-43db-b97c-5687c571b2af.png)

**Comment by Mawiel** [comment]
Hello. Did you ever find a fix for this? Sometimes these types of errors are fixed after deleting Saved and Intermediate folders.
